---
title: "Democracy & Macroeconomics"
author: "Jacob Lillelund"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Set working directory
knitr::opts_knit$set(root.dir = "/Users/jacoblillelund/Documents/applied-social-science/data")

library(readxl)
library(janitor)
library(tidyverse)
```

# Load and clean data
```{r}
### FREEDOM HOUSE ###
# import and clean
freedomhouse <- read_excel("All_data_FIW_2013-2022.xlsx", sheet = 2, skip = 1, col_names = TRUE)
freedomhouse <- freedomhouse %>% 
  clean_names() %>%                                            # tidy data with janitor-package
  rename(country = country_territory, year = edition ) %>%     # rename columns
  select(c("country", "region", "c_t", "year", "pr", "cl", "total"))  # select relevant columns

### DEMOCRACY MATRIX RANKING ###
democracy_matrix <- read_excel("democracy-matrix-ranking.xlsx", skip = 1, col_names = TRUE)
democracy_matrix <- democracy_matrix %>% 
  clean_names() %>%                  # tidy data with janitor-package
  select(country, total_value_index) # select columns

### MACROECONOMIC VARIABLES ###
# Import and clean
worlddatabank <- read_csv("worlddatabank.csv",show_col_types = FALSE) %>%  
  rename_at(vars(5:11), ~ substr(., 1, 4)) %>%   # rename "year"-columns
  mutate_at(vars(5:11), as.integer) %>%          # convert observations to integers
  select(-c("Country Code")) %>%                 # exclude irrelevant column(s)
  rename("country" = "Country Name", economic_variable = "Series Name")
  
# create long-format-version
worlddatabank_long <- pivot_longer(worlddatabank, 
  cols = 4:10, names_to = "year", values_to = "value") %>% # create long format on year variable
  mutate(year = as.integer(year))
```

# Compare democracy-indexes
```{r}
# Merge dataframes
index_comparison <- freedomhouse %>% filter(year == 2020) %>% 
  left_join(democracy_matrix, by = "country") %>% 
  select(country, total, total_value_index) %>%  # select relevant columns
  filter(!is.na(total_value_index)) %>% # filter for rows with missing values (territories are not included in Democracy Matrix ranking)
  mutate(total_value_index = total_value_index/10) # scale the democracy ranking to 0-100 from 0-1000

# Draw Scatterplot
index_comparison %>% 
  ggplot(aes(x = total, y = total_value_index, label = country)) +
  geom_text() +
  geom_smooth(method = "lm", se = FALSE)

# Check correlation
cor(index_comparison$total, index_comparison$total_value_index)
```

### Create country-subsets of data ###

```{r}
# EEA Subset
eea <- c()

# OECD Subset
oecd <- 

# EEA + OECD Subset
  
oecd_eea <-   
```

# Missing data for each subset
```{r}
# Extract variable names
economic_variable <- unique(na.omit(worlddatabank[,2],)) # extract variable strings

# Initiate missing-data dataframe 
missing_data_allcountries <- tibble(economic_variable)


for (unique_variable in missing_data_allcountries$economic_variable) {
  
  for (year in c("2013", "2014", "2015", "2016", "2017", "2018", "2019")) {
  
  na <- worlddatabank %>%
            filter(economic_variable == unique_variable) %>% 
            select(year) %>% 
            summarize(num_na = sum(is.na(.)))
  total <- worlddatabank %>%
            filter(economic_variable == unique_variable) %>% 
            select(year) %>% 
            nrow()

  missing_percentage <- as.numeric(na/total)

  missing_data_allcountries[[year]][missing_data_allcountries$economic_variable == unique_variable] <- missing_percentage
  }
  
}

missing_data_allcountries <- rbind(missing_data_allcountries, c("Mean Missing Percentage", colMeans(missing_data_allcountries[1:5,2:8])))
```

# Merge dataframes for modelling
```{r}
# Write CSV files for Python
  # write.csv(freedomhouse, "freedomhouse.csv", row.names = FALSE)
  # write.csv(worlddatabank, "worlddatabank_clean.csv", row.names = FALSE)
  # write.csv(worlddatabank_long, "worlddatabank_clean_long.csv", row.names = FALSE)

# Dirty_cat merging in Python - Open Provided Python Script

# Load Python dataset
```


# Exploratory Data Analysis
```{r}

```

