---
title: "freedom-house"
author: "Jacob Lillelund"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Call packages and load data
```{r}
library(readxl)
library(janitor)
library(tidyverse)

setwd("/Users/jacoblillelund/Documents/applied-social-science")

# load data 

# FREEDOM HOUSE
fw_data <- read_excel("All_data_FIW_2013-2022.xlsx", sheet = 2, skip = 1, col_names = TRUE)

fw_data <- fw_data %>% # tidy data with janitor-package
  clean_names()

fw_data <- fw_data %>% rename(country = country_territory) # rename column

# DEMOCRACY MATRIX RANKING
dmr_data <- read_excel("democracy-matrix-ranking.xlsx", skip = 1, col_names = TRUE)
dmr_data <- dmr_data %>% # tidy data with janitor-package
  clean_names()

dmr_data <- dmr_data %>% select(country, total_value_index) # select values
```
# Compare the two ranking projects
```{r}
# Merge dataframes

fw_data_mergeready <-  fw_data %>% filter(edition == 2020) # filter for relevant year

# join the two data frames by the 'country' column
merged_data <- left_join(fw_data_mergeready, dmr_data, by = "country")

# Wrangle
merged_data_total_values <- merged_data %>%  
  select(country, total, total_value_index) %>%  # select relevant columns
  filter(!is.na(total_value_index)) %>% # filter for rows with missing values (territories are not included in Democracy Matrix ranking)
  mutate(total_value_index = total_value_index/10) # scale the democracy ranking to 0-100 from 0-1000

# Draw Scatterplot
merged_data_total_values %>% 
  ggplot(aes(x = total, y = total_value_index, label = country)) +
  geom_text() +
  geom_smooth(method = "lm", se = FALSE)

# Check correlation
cor(merged_data_total_values$total, merged_data_total_values$total_value_index)
```


# Exploratory Data Analysis
```{r}
inspect <- raw_data %>% select(country_territory, edition, a, b, c, add_q, add_a, pr, d, e, f, g, cl, total)
inspect
```

