---
title: "Democracy & Macroeconomics"
author: "Jonathan"
date: "2023-02-28"
output: html_document
---

# Call packages and load data
```{r setup}
library(tidyverse)

setwd("C:/Users/jonat/OneDrive/Desktop/University/Assignments/2. Semester/Applied Cognitive Science/Repository/applied-social-science")

```

```{r}

wdb <- read_csv("Repository/applied-social-science/data/worlddatabank_clean.csv")

```

```{r}


unique <- unique(na.omit(is.numeric(wdb[0,])))

```


```{r}

economic_variables <- unique(na.omit(WDB[,2], ))

missing_data <- data_frame(economic_variable = economic_variables
  )


for (ev in missing_data$economic_variable) {
  
  for (year in c("2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")) {
  
  n_na <- wdb %>%
            filter(economic_variable == ev) %>% 
            select(year) %>% 
            summarize(num_na = sum(is.na(.)))
  n_total <- wdb %>%
            filter(economic_variable == ev) %>% 
            select(year) %>% 
            nrow()

  md <- as.numeric(n_na/n_total)

  missing_data[[year]][missing_data$economic_variable == ev] <- md
  }
  
}

missing_data <- rbind(missing_data, c("mean percentage", colMeans(missing_data[1:5,2:9])))


```

