---
title: "NA-Values-Function"
author: "Jonathan"
date: "2023-04-20"
output: pdf_document
---

# Call packages and load data
```{r setup}
library(tidyverse)
library(dplyr)
setwd("C:/Users/jonat/OneDrive/Desktop/University/Assignments/2. Semester/Applied Cognitive Science/Repository/applied-social-science")

```

```{r}

wdb <- read_csv("Repository/applied-social-science/data/worlddatabank.csv")

```

```{r}

missing_data_function <- function(data_file) {
  
  temp <- data_file[, c("Country Name", "Series Name")]

  temp <- cbind(temp, data_file[, 5:ncol(data_file)])

  temp <- rename_at(temp, vars(3:ncol(temp)), ~ substr(., 1, 4))

  temp <- rename(temp, "country" = "Country Name", variable = "Series Name")

  temp[, 3:ncol(temp)] <- lapply(temp[, 3:ncol(temp)], as.numeric)
  
  data_file <- temp
  
  col_names <- colnames(data_file)

  years <- col_names[3:length(col_names)]

  variables <- unique(na.omit(data_file[,2]))

  missing_data <- data.frame(variable = variables)

  for (v in missing_data$variable) {
    for (year in years) {
  
      n_na <- data_file %>%
        filter(variable == v) %>% 
        select(year) %>% 
        summarize(num_na = sum(is.na(.)))
      
      n_total <- data_file %>%
        filter(variable == v) %>% 
        select(year) %>% 
        nrow()

      md <- as.numeric(n_na/n_total)

      missing_data[missing_data$variable == v, year] <- md
    }
  }

  row_means <- rowMeans(missing_data[1:nrow(missing_data),2:ncol(missing_data)], na.rm = TRUE)
  col_means <- colMeans(missing_data[1:nrow(missing_data),2:ncol(missing_data)], na.rm = TRUE)

  missing_data <- rbind(missing_data, c("mean col", col_means))
  missing_data$mean_row <- c(row_means, NA)
  
  df_col_means <- data.frame(years, col_means)

  col_means_plot <- ggplot(df_col_means, aes(x = years, y = col_means, fill = years)) +
                    geom_bar(stat = "identity") +
                    labs(x = "Year", y = "Missing Data", title = "Missing Data per year")
  

  df_row_means <- data.frame(variables, row_means)

  row_means_plot <- ggplot(df_row_means, aes(x = variables, y = row_means, fill = variables)) +
                    geom_bar(stat = "identity") +
                    labs(x = "Variable", y = "Missing Data", title = "Missing data per variable") +
                    theme(axis.text.x = element_text(angle = 90, size = 8, hjust = 1))



  

list(missing_data, col_means_plot, row_means_plot)
}

```

```{r warning=FALSE}

missing_data_function(wdb)

```














